#!/bin/bash

# Useful for writing/debugging webhosting scripts

echo ""
echo "Key environment variables that can be expected/used in all webhosting scripts:"
echo ""
echo "               USER = $USER"
echo "               HOME = $HOME"
echo "     WH_CURRENT_DIR = $WH_CURRENT_DIR"
echo "        WH_BASE_DIR = $WH_BASE_DIR"
echo "      WH_SCRIPT_DIR = $WH_SCRIPT_DIR"
echo "          PYENV_DIR = $PYENV_DIR"
echo "      PYENV_VERSION = $PYENV_VERSION"
echo "            WH_USER = $WH_USER"
echo "            WH_SITE = $WH_SITE"
echo "      WH_USER_VALID = $WH_USER_VALID"
echo "      WH_SITE_VALID = $WH_SITE_VALID"
echo "WH_LARAVEL_DETECTED = $WH_LARAVEL_DETECTED"
echo "   WH_VITE_DETECTED = $WH_VITE_DETECTED"
echo "WH_VUE2_EXTRA_BUILD = $WH_VUE2_EXTRA_BUILD"
echo "WH_VUE3_EXTRA_BUILD = $WH_VUE3_EXTRA_BUILD"
echo " WH_SITE_NGINX_FILE = $WH_SITE_NGINX_FILE"
echo "         WH_PHP_CMD = $WH_PHP_CMD"
echo "     WH_PHP_VERSION = $WH_PHP_VERSION"
echo "     WH_WEBROOT_DIR = $WH_WEBROOT_DIR"
echo "     WH_PROJECT_DIR = $WH_PROJECT_DIR"
echo "     WH_PROJECT_ENV = $WH_PROJECT_ENV"
echo "        WH_APP_NAME = $WH_APP_NAME"
echo ""
